// flow-typed signature: 8e8a65bf0fca7df271462ce808f8bd7a
// flow-typed version: <<STUB>>/emojione_v2.2.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emojione'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emojione' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emojione/gruntfile' {
  declare module.exports: any;
}

declare module 'emojione/lib/android/generator/generate' {
  declare module.exports: any;
}

declare module 'emojione/lib/emojione-awesome/generate' {
  declare module.exports: any;
}

declare module 'emojione/lib/ios/generator/generate' {
  declare module.exports: any;
}

declare module 'emojione/lib/js/emojione' {
  declare module.exports: any;
}

declare module 'emojione/lib/js/emojione.min' {
  declare module.exports: any;
}

declare module 'emojione/lib/js/tests/generate' {
  declare module.exports: any;
}

declare module 'emojione/lib/meteor/emojione-client' {
  declare module.exports: any;
}

declare module 'emojione/lib/meteor/post-export' {
  declare module.exports: any;
}

declare module 'emojione/lib/meteor/pre-export' {
  declare module.exports: any;
}

declare module 'emojione/package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emojione/gruntfile.js' {
  declare module.exports: $Exports<'emojione/gruntfile'>;
}
declare module 'emojione/lib/android/generator/generate.js' {
  declare module.exports: $Exports<'emojione/lib/android/generator/generate'>;
}
declare module 'emojione/lib/emojione-awesome/generate.js' {
  declare module.exports: $Exports<'emojione/lib/emojione-awesome/generate'>;
}
declare module 'emojione/lib/ios/generator/generate.js' {
  declare module.exports: $Exports<'emojione/lib/ios/generator/generate'>;
}
declare module 'emojione/lib/js/emojione.js' {
  declare module.exports: $Exports<'emojione/lib/js/emojione'>;
}
declare module 'emojione/lib/js/emojione.min.js' {
  declare module.exports: $Exports<'emojione/lib/js/emojione.min'>;
}
declare module 'emojione/lib/js/tests/generate.js' {
  declare module.exports: $Exports<'emojione/lib/js/tests/generate'>;
}
declare module 'emojione/lib/meteor/emojione-client.js' {
  declare module.exports: $Exports<'emojione/lib/meteor/emojione-client'>;
}
declare module 'emojione/lib/meteor/post-export.js' {
  declare module.exports: $Exports<'emojione/lib/meteor/post-export'>;
}
declare module 'emojione/lib/meteor/pre-export.js' {
  declare module.exports: $Exports<'emojione/lib/meteor/pre-export'>;
}
declare module 'emojione/package.js' {
  declare module.exports: $Exports<'emojione/package'>;
}
